"""notifications retry_count

Revision ID: 68d07710c0bf
Revises: b2c3d4e5f6a7
Create Date: 2026-06-13 00:44:35.370081

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '68d07710c0bf'
down_revision: str | None = 'b2c3d4e5f6a7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'retry_count')
    # ### end Alembic commands ###
