"""initial schema

Revision ID: fcfa2fd7c22c
Revises: 
Create Date: 2026-06-12 17:35:53.542747

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.core.rls import downgrade_sql as rls_downgrade_sql
from app.core.rls import upgrade_sql as rls_upgrade_sql

revision: str = 'fcfa2fd7c22c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # citext powers case-insensitive unique emails (users.email); must exist
    # before the users table is created below.
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event', sa.Text(), nullable=False),
    sa.Column('props', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_events'))
    )
    op.create_index('ix_analytics_events_event_time', 'analytics_events', ['event', 'created_at'], unique=False)
    op.create_index('ix_analytics_events_org_event', 'analytics_events', ['org_id', 'event'], unique=False)
    op.create_table('organizations',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('timezone', sa.Text(), server_default='Asia/Kolkata', nullable=False),
    sa.Column('plan', sa.Text(), server_default='free', nullable=False),
    sa.Column('report_card_hour', sa.Integer(), server_default='18', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("plan IN ('free', 'pro')", name=op.f('ck_organizations_plan_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_table('users',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('phone', name=op.f('uq_users_phone'))
    )
    op.create_table('auth_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("purpose IN ('magic_link', 'otp', 'invite', 'refresh')", name=op.f('ck_auth_tokens_purpose_valid')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_auth_tokens_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_auth_tokens_token_hash'))
    )
    op.create_index('ix_auth_tokens_user_purpose', 'auth_tokens', ['user_id', 'purpose'], unique=False)
    op.create_table('boards',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('visibility', sa.Text(), server_default='public', nullable=False),
    sa.Column('category', sa.Text(), server_default='tasks', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('tasks', 'checklist')", name=op.f('ck_boards_category_valid')),
    sa.CheckConstraint("visibility IN ('public', 'private')", name=op.f('ck_boards_visibility_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_boards_created_by_users')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_boards_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_boards_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_boards'))
    )
    op.create_index('ix_boards_org_visibility', 'boards', ['org_id', 'visibility'], unique=False)
    op.create_table('device_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("platform IN ('fcm', 'webpush')", name=op.f('ck_device_tokens_platform_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_device_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_tokens')),
    sa.UniqueConstraint('token', name=op.f('uq_device_tokens_token'))
    )
    op.create_index('ix_device_tokens_user', 'device_tokens', ['user_id'], unique=False)
    op.create_table('memberships',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('org_role', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='active', nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notification_prefs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('token_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("org_role IN ('admin', 'member')", name=op.f('ck_memberships_org_role_valid')),
    sa.CheckConstraint("status IN ('active', 'removed')", name=op.f('ck_memberships_status_valid')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_memberships_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('org_id', 'user_id', name=op.f('uq_memberships_org_id'))
    )
    op.create_index('ix_memberships_user_status', 'memberships', ['user_id', 'status'], unique=False)
    op.create_table('board_members',
    sa.Column('board_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('board_role', sa.Text(), server_default='member', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], name=op.f('fk_board_members_board_id_boards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_board_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_board_members')),
    sa.UniqueConstraint('board_id', 'user_id', name=op.f('uq_board_members_board_id'))
    )
    op.create_table('task_templates',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('board_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('recurrence_rule', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('default_assignee_id', sa.UUID(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_critical', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('remind_before_minutes', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], name=op.f('fk_task_templates_board_id_boards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_task_templates_created_by_users')),
    sa.ForeignKeyConstraint(['default_assignee_id'], ['users.id'], name=op.f('fk_task_templates_default_assignee_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_task_templates_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_templates'))
    )
    op.create_index('ix_task_templates_org_active', 'task_templates', ['org_id', 'active'], unique=False)
    op.create_table('task_instances',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('board_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('occurrence_date', sa.Date(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('all_day', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status', sa.Text(), server_default='open', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('pass_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_critical', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('remind_before_minutes', sa.Integer(), server_default='30', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('open', 'done', 'missed', 'cancelled')", name=op.f('ck_task_instances_status_valid')),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name=op.f('fk_task_instances_assignee_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], name=op.f('fk_task_instances_board_id_boards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], name=op.f('fk_task_instances_completed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_task_instances_created_by_users')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_task_instances_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['task_templates.id'], name=op.f('fk_task_instances_template_id_task_templates'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_instances'))
    )
    op.create_index('ix_task_instances_board', 'task_instances', ['board_id', 'status', 'due_at'], unique=False)
    op.create_index('ix_task_instances_home', 'task_instances', ['org_id', 'assignee_id', 'status', 'due_at'], unique=False)
    op.create_index('uq_task_instances_template_occurrence', 'task_instances', ['template_id', 'occurrence_date'], unique=True, postgresql_where=sa.text('template_id IS NOT NULL'))
    op.create_table('attachments',
    sa.Column('instance_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('note', 'photo')", name=op.f('ck_attachments_kind_valid')),
    sa.ForeignKeyConstraint(['instance_id'], ['task_instances.id'], name=op.f('fk_attachments_instance_id_task_instances'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_attachments_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments'))
    )
    op.create_table('notifications',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('instance_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('notif_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dedupe_key', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("channel IN ('whatsapp', 'push', 'email')", name=op.f('ck_notifications_channel_valid')),
    sa.CheckConstraint("notif_type IN ('assigned', 'passed', 'reminder', 'overdue', 'digest', 'report_card', 'nudge')", name=op.f('ck_notifications_notif_type_valid')),
    sa.CheckConstraint("status IN ('pending', 'sent', 'failed')", name=op.f('ck_notifications_status_valid')),
    sa.ForeignKeyConstraint(['instance_id'], ['task_instances.id'], name=op.f('fk_notifications_instance_id_task_instances'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_notifications_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_notifications_dedupe_key'))
    )
    op.create_index('ix_notifications_sweep', 'notifications', ['status', 'scheduled_at'], unique=False)
    op.create_table('task_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('instance_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type IN ('created', 'assigned', 'claimed', 'passed', 'completed', 'reopened', 'missed', 'commented', 'attached', 'edited', 'cancelled')", name=op.f('ck_task_events_event_type_valid')),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_task_events_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instance_id'], ['task_instances.id'], name=op.f('fk_task_events_instance_id_task_instances'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_events'))
    )
    op.create_index('ix_task_events_instance', 'task_events', ['instance_id', 'id'], unique=False)
    op.create_index('ix_task_events_org_type_time', 'task_events', ['org_id', 'event_type', 'created_at'], unique=False)
    # ### end Alembic commands ###

    # Org-isolation RLS safety net (engages once app.current_org_id is set).
    for stmt in rls_upgrade_sql():
        op.execute(stmt)


def downgrade() -> None:
    for stmt in rls_downgrade_sql():
        op.execute(stmt)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_events_org_type_time', table_name='task_events')
    op.drop_index('ix_task_events_instance', table_name='task_events')
    op.drop_table('task_events')
    op.drop_index('ix_notifications_sweep', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('attachments')
    op.drop_index('uq_task_instances_template_occurrence', table_name='task_instances', postgresql_where=sa.text('template_id IS NOT NULL'))
    op.drop_index('ix_task_instances_home', table_name='task_instances')
    op.drop_index('ix_task_instances_board', table_name='task_instances')
    op.drop_table('task_instances')
    op.drop_index('ix_task_templates_org_active', table_name='task_templates')
    op.drop_table('task_templates')
    op.drop_table('board_members')
    op.drop_index('ix_memberships_user_status', table_name='memberships')
    op.drop_table('memberships')
    op.drop_index('ix_device_tokens_user', table_name='device_tokens')
    op.drop_table('device_tokens')
    op.drop_index('ix_boards_org_visibility', table_name='boards')
    op.drop_table('boards')
    op.drop_index('ix_auth_tokens_user_purpose', table_name='auth_tokens')
    op.drop_table('auth_tokens')
    op.drop_table('users')
    op.drop_table('organizations')
    op.drop_index('ix_analytics_events_org_event', table_name='analytics_events')
    op.drop_index('ix_analytics_events_event_time', table_name='analytics_events')
    op.drop_table('analytics_events')
    # ### end Alembic commands ###
